"""Constants for Atlas Scientific Pool integration."""

from __future__ import annotations

DOMAIN = "atlas_scientific_pool"

PLATFORMS = ["sensor", "number", "button", "binary_sensor", "switch", "select"]

CONF_CHEMISTRY_NODE = "chemistry_node"
CONF_PRESSURE_NODE = "pressure_node"
CONF_LEVEL_NODE = "level_node"
CONF_PUMP_NODE = "pump_node"
CONF_HEAT_PUMP_NODE = "heat_pump_node"

CONF_PUMP_ENABLED = "pump_enabled"
CONF_HEAT_PUMP_ENABLED = "heat_pump_enabled"
CONF_PRESSURE_ENABLED = "pressure_enabled"
CONF_LEVEL_ENABLED = "level_enabled"

CONF_SCAN_INTERVAL = "scan_interval"
CONF_ENABLE_CONTROLS = "enable_controls"
CONF_WINTER_MODE = "winter_mode"
CONF_MAX_CHLORINE_DOSE_ML = "max_chlorine_dose_ml"
CONF_MAX_ACID_DOSE_ML = "max_acid_dose_ml"
CONF_CHLORINE_COOLDOWN_SECONDS = "chlorine_cooldown_seconds"
CONF_ACID_COOLDOWN_SECONDS = "acid_cooldown_seconds"
CONF_DEFAULT_CHLORINE_DOSE_ML = "default_chlorine_dose_ml"
CONF_DEFAULT_ACID_DOSE_ML = "default_acid_dose_ml"
CONF_ENABLE_ORP_AUTOMATION = "enable_orp_automation"
CONF_DEFAULT_TARGET_ORP = "default_target_orp"
CONF_ORP_SENSOR_OBJECT_ID = "orp_sensor_object_id"
CONF_ORP_HYSTERESIS_MV = "orp_hysteresis_mv"
CONF_ENABLE_LEVEL_AUTOMATION = "enable_level_automation"
CONF_DEFAULT_TARGET_WATER_LEVEL_PERCENT = "default_target_water_level_percent"
CONF_LEVEL_HYSTERESIS_PERCENT = "level_hysteresis_percent"
CONF_LEVEL_SENSOR_OBJECT_ID = "level_sensor_object_id"
CONF_FILL_DEVICE_NAME = "fill_device_name"
CONF_FILL_SWITCH_OBJECT_ID = "fill_switch_object_id"
CONF_FILL_START_BUTTON_OBJECT_ID = "fill_start_button_object_id"
CONF_FILL_STOP_BUTTON_OBJECT_ID = "fill_stop_button_object_id"
CONF_FILL_RUNNING_BINARY_SENSOR_OBJECT_ID = "fill_running_binary_sensor_object_id"
CONF_MAX_FILL_RUNTIME_MINUTES = "max_fill_runtime_minutes"
CONF_POOL_VOLUME_LITERS = "pool_volume_liters"
CONF_CHLORINE_STRENGTH_PERCENT = "chlorine_strength_percent"
CONF_MAX_PPM_INCREASE_PER_DOSE = "max_ppm_increase_per_dose"
CONF_ACID_STRENGTH_PERCENT = "acid_strength_percent"
CONF_MAX_PH_DROP_PER_DOSE = "max_ph_drop_per_dose"

CONF_ENABLE_NOTIFICATIONS = "enable_notifications"
CONF_NOTIFY_SERVICE = "notify_service"
CONF_PH_SENSOR_OBJECT_ID = "ph_sensor_object_id"
CONF_PH_MIN_THRESHOLD = "ph_min_threshold"
CONF_PH_MAX_THRESHOLD = "ph_max_threshold"
CONF_ORP_ALERT_THRESHOLD = "orp_alert_threshold"
CONF_NOTIFICATION_COOLDOWN_MINUTES = "notification_cooldown_minutes"
CONF_EXPOSE_RAW_PUMP_SWITCHES = "expose_raw_pump_switches"
CONF_ENABLE_PUMP_SPEED_ABSTRACTION = "enable_pump_speed_abstraction"
CONF_PUMP_POWER_SWITCH_OBJECT_ID = "pump_power_switch_object_id"
CONF_PUMP_SPEED_LOW_SWITCH_OBJECT_ID = "pump_speed_low_switch_object_id"
CONF_PUMP_SPEED_MEDIUM_SWITCH_OBJECT_ID = "pump_speed_medium_switch_object_id"
CONF_PUMP_SPEED_HIGH_SWITCH_OBJECT_ID = "pump_speed_high_switch_object_id"

CONF_CHLORINE_VOLUME_NUMBER = "chlorine_volume_number"
CONF_ACID_VOLUME_NUMBER = "acid_volume_number"
CONF_CHLORINE_DOSE_BUTTON = "chlorine_dose_button"
CONF_ACID_DOSE_BUTTON = "acid_dose_button"
CONF_CHLORINE_STOP_BUTTON = "chlorine_stop_button"
CONF_ACID_STOP_BUTTON = "acid_stop_button"

CONF_CHLORINE_RUNNING_BINARY_SENSOR = "chlorine_running_binary_sensor"
CONF_ACID_RUNNING_BINARY_SENSOR = "acid_running_binary_sensor"

DEFAULT_SCAN_INTERVAL = 30
DEFAULT_ENABLE_CONTROLS = True
DEFAULT_WINTER_MODE = False
DEFAULT_PUMP_ENABLED = True
DEFAULT_HEAT_PUMP_ENABLED = True
DEFAULT_PRESSURE_ENABLED = True
DEFAULT_LEVEL_ENABLED = True
DEFAULT_MAX_CHLORINE_DOSE_ML = 150.0
DEFAULT_MAX_ACID_DOSE_ML = 100.0
DEFAULT_CHLORINE_COOLDOWN_SECONDS = 1800
DEFAULT_ACID_COOLDOWN_SECONDS = 1800
DEFAULT_CHLORINE_DOSE_ML = 50.0
DEFAULT_ACID_DOSE_ML = 25.0
DEFAULT_ENABLE_ORP_AUTOMATION = False
DEFAULT_TARGET_ORP = 700.0
DEFAULT_ORP_SENSOR_OBJECT_ID = "orp"
DEFAULT_ORP_HYSTERESIS_MV = 15.0
DEFAULT_ENABLE_LEVEL_AUTOMATION = False
DEFAULT_TARGET_WATER_LEVEL_PERCENT = 85.0
DEFAULT_LEVEL_HYSTERESIS_PERCENT = 3.0
DEFAULT_LEVEL_SENSOR_OBJECT_ID = "pool_level"
DEFAULT_FILL_DEVICE_NAME = ""
DEFAULT_FILL_SWITCH_OBJECT_ID = ""
DEFAULT_FILL_START_BUTTON_OBJECT_ID = ""
DEFAULT_FILL_STOP_BUTTON_OBJECT_ID = ""
DEFAULT_FILL_RUNNING_BINARY_SENSOR_OBJECT_ID = ""
DEFAULT_MAX_FILL_RUNTIME_MINUTES = 45
DEFAULT_POOL_VOLUME_LITERS = 50000.0
DEFAULT_CHLORINE_STRENGTH_PERCENT = 12.5
DEFAULT_MAX_PPM_INCREASE_PER_DOSE = 0.3
DEFAULT_ACID_STRENGTH_PERCENT = 10.0
DEFAULT_MAX_PH_DROP_PER_DOSE = 0.1

DEFAULT_ENABLE_NOTIFICATIONS = False
DEFAULT_NOTIFY_SERVICE = ""
DEFAULT_PH_SENSOR_OBJECT_ID = "ph"
DEFAULT_PH_MIN_THRESHOLD = 7.2
DEFAULT_PH_MAX_THRESHOLD = 7.8
DEFAULT_ORP_ALERT_THRESHOLD = 600.0
DEFAULT_NOTIFICATION_COOLDOWN_MINUTES = 60
DEFAULT_EXPOSE_RAW_PUMP_SWITCHES = False
DEFAULT_ENABLE_PUMP_SPEED_ABSTRACTION = True
DEFAULT_PUMP_POWER_SWITCH_OBJECT_ID = "relay4"
DEFAULT_PUMP_SPEED_LOW_SWITCH_OBJECT_ID = "relay3"
DEFAULT_PUMP_SPEED_MEDIUM_SWITCH_OBJECT_ID = "relay2"
DEFAULT_PUMP_SPEED_HIGH_SWITCH_OBJECT_ID = "relay1"

ALERT_ORP_LOW = "orp_low"
ALERT_PH_LOW = "ph_low"
ALERT_PH_HIGH = "ph_high"

DEFAULT_CHLORINE_VOLUME_NUMBER = "volume_cl"
DEFAULT_ACID_VOLUME_NUMBER = "volume_acid"
DEFAULT_CHLORINE_DOSE_BUTTON = "dose_clorine_over_time"
DEFAULT_ACID_DOSE_BUTTON = "dose_acid_over_time"
DEFAULT_CHLORINE_STOP_BUTTON = "stop_cl_pump"
DEFAULT_ACID_STOP_BUTTON = "stop_acid_pump"
DEFAULT_CHLORINE_RUNNING_BINARY_SENSOR = "pump_cl_state"
DEFAULT_ACID_RUNNING_BINARY_SENSOR = "pump_acid_state"

ROLE_CHEMISTRY = "chemistry"
ROLE_PRESSURE = "pressure"
ROLE_LEVEL = "level"
ROLE_PUMP = "pump"
ROLE_HEAT_PUMP = "heat_pump"
NODE_ROLES = (ROLE_CHEMISTRY, ROLE_PRESSURE, ROLE_LEVEL, ROLE_PUMP, ROLE_HEAT_PUMP)
